<footer class="footer">
    <div class="footer__container">
        <div class="footer__container--row">
            <div class="footer__container--col footer__container--col--1">
                <h4 class="footer__container--col--title">Our group</h4>
                <ul class="footer__container--col__lists">
                    <li class="footer__container--col--name"><a href="mailto:104993925@student.swin.edu.au"
                            class="footer__container--col--name--link">Tran&nbsp;Buu&nbsp;Duc&nbsp;Tri</a>
                    </li>
                    <li class="footer__container--col--name"><a href="malito:104992981@student.swin.edu.au"
                            class="footer__container--col--name--link">Nguyen&nbsp;Duy&nbsp;Quang</a>
                    </li>
                    <li class="footer__container--col--name"><a href="mailto:104841290@student.swin.edu.au"
                            class="footer__container--col--name--link">Le&nbsp;Hac&nbsp;Du</a>
                    </li>
                </ul>
            </div>
            <div class="footer__container--col footer__container--col--2">
                <h4 class="footer__container--col--title">Follow Us</h4>
                <div class="footer__container--col--social_link">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
</footer>